x-default-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

services:
  postgres:
    logging: *default-logging
  auth-mysql:
    logging: *default-logging
  auth-redis:
    logging: *default-logging
  auth-migrate:
    logging: *default-logging
  auth-bootstrap:
    logging: *default-logging
  auth:
    logging: *default-logging
  app:
    logging: *default-logging

